# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_auto_20170219_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, upload_to='image'),
        ),
    ]
