# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_auto_20170219_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
