# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_auto_20170219_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.Profile'),
        ),
    ]
