# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0009_auto_20170220_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
